#ifndef INSECTS_DATA_H
#define INSECTS_DATA_H

// Char-maps dos inimigos insetos (por tamanho), gerados por script. Legenda:
//   . vazio · o contorno · b corpo(cor da familia) · h brilho · w asa · e olho · l pata
// besouro=quadrado, mosca=triangulo, aranha=pentagono. Pintados em tilegen.c.

static const char *const INS_BEETLE16[16] =
{
    "....l......l....",
    ".....llooll.....",
    "......ebeo......",
    ".....obbbbo.....",
    ".....oobooo.....",
    "....oooooooo....",
    "....ohhbobbo....",
    "..loohhbobbool..",
    "ll.obhhbobbbo.ll",
    "...obbbbobbbo...",
    "...obbbbobbbo...",
    "..lobbbbobbbol..",
    "ll..obbbobbo..ll",
    "....obbbobbo....",
    ".....obbobo.....",
    "......oooo......",
};

static const char *const INS_BEETLE24[24] =
{
    "......l..........l......",
    ".......ll..oo..ll.......",
    ".........lobbol.........",
    "........oobbbboo........",
    "........oebbbebo........",
    "........obbbbbbo........",
    "........obbbobbo........",
    ".......oboobooobo.......",
    "......obhhboobbbbo......",
    "....llohhhbbobbbbol.....",
    "..lllobhhhhbobbbbboll...",
    "lllllobhhhbbobbbbbollll.",
    "lll..obbhhbbobbbbbo.lll.",
    ".....obbbbbbobbbbbo.....",
    ".....obbbbbbobbbbbo.....",
    "....lobbbbbbobbbbbo.....",
    "..lllobbbbbbobbbbboll...",
    "lllllobbbbbbobbbbbollll.",
    "lll...obbbbbobbbbo..lll.",
    "......obbbbbobbbbo......",
    ".......obbbbobbbo.......",
    ".......oobbbobboo.......",
    "........oobboboo........",
    "..........oooo..........",
};

static const char *const INS_BEETLE32[32] =
{
    "........l..............l........",
    ".........l............l.........",
    "..........ll.oooooo.ll..........",
    "............lbbbbbbl............",
    "...........obbbbbbbbo...........",
    "...........oebbbbbebo...........",
    "...........obbbbbbbbo...........",
    "...........obbbbbbbbo...........",
    "..........oobbbbobbboo..........",
    ".........oobobbbobboboo.........",
    ".........obbboooooobbbo.........",
    "........obhhhbbbobbbbbbo........",
    ".......lobhhhhbbobbbbbbo........",
    ".....llobbhhhhbbobbbbbbbol......",
    "...llllobbhhhhbbobbbbbbbolll....",
    ".lllll.obbhhhhbbobbbbbbbolllll..",
    "llll...obbhhhbbbobbbbbbbo..llll.",
    "ll....obbbbbbbbbobbbbbbbbo...ll.",
    "......obbbbbbbbbobbbbbbbbo......",
    "......obbbbbbbbbobbbbbbbbo......",
    "......obbbbbbbbbobbbbbbbbo......",
    "....lllobbbbbbbbobbbbbbboll.....",
    "..lllllobbbbbbbbobbbbbbbollll...",
    "lllll..obbbbbbbbobbbbbbbo.lllll.",
    "lll....obbbbbbbbobbbbbbbo...lll.",
    "........obbbbbbbobbbbbbo........",
    "........oobbbbbbobbbbboo........",
    ".........obbbbbbobbbbbo.........",
    "..........obbbbbobbbbo..........",
    "...........obbbbobbbo...........",
    "............ooobbooo............",
    "...............oo...............",
};

static const char *const INS_FLY16[16] =
{
    "................",
    ".......oo.......",
    ".....ooeeoo.....",
    ".....oeoeeo.....",
    "...wwoeeeeoww...",
    "...wwwoooowww...",
    "..wwwwobbowwww..",
    ".wwww.obbo.wwww.",
    "www..obbbbo..www",
    ".w...oooooo...w.",
    ".....obbbbo.....",
    "......obbo......",
    ".....oooooo.....",
    "......obbo......",
    ".......ll.......",
    "......l..l......",
};

static const char *const INS_SPIDER24[24] =
{
    "........................",
    "........................",
    "........................",
    "........................",
    ".lllll............lllll.",
    "......l..oooooo..l......",
    ".......lobbbbbbol.......",
    ".......obebebebbo.......",
    "llllll.obbbbbbbbo.llllll",
    "......lobbbbbbbbol......",
    ".......oobbbbbboo.......",
    "......ooboobbooboo......",
    "..llllobbboooobbbollll..",
    "ll....obbbbhhbbbbo....ll",
    ".....obbbbhhhhbbbbo.....",
    ".....obbbbhhhhbbbbo.....",
    "....lobbbbhhhhbbbbol....",
    "..ll..obbbbhhbbbbo..ll..",
    ".l....obbbbbbbbbbo....l.",
    "......oobbbbbbbboo......",
    ".......oobbbbbboo.......",
    "........ooobbooo........",
    "...........oo...........",
    "........................",
};

static const char *const INS_SPIDER32[32] =
{
    "................................",
    "................................",
    "................................",
    "................................",
    ".lllllll...............lllllll..",
    ".llllllll.............llllllll..",
    ".......lll...oooooo..lll........",
    "........lll.obbbbbbolll.........",
    ".........llobbbbbbbbol..........",
    "..........obebbebbebbo..........",
    "llllllll..obbbbbbbbbbo.lllllllll",
    "llllllllllobbbbbbbbbbollllllllll",
    ".......lllobbbbbbbbbboll........",
    "..........obbbbbbbbbbo..........",
    ".........obobbbbbbbbobo.........",
    "........obbboobbbboobbbo........",
    "llllllllobbbbboooobbbbbollllllll",
    "lllllllobbbbbbhhhhbbbbbbolllllll",
    ".......obbbbbbhhhhbbbbbbo.......",
    ".......obbbbbbhhhhbbbbbbo.......",
    ".......obbbbbbhhhhbbbbbbo.......",
    ".....llobbbbbbhhhhbbbbbbol......",
    "...llllobbbbbbhhhhbbbbbbolll....",
    ".lllll..obbbbbbhhbbbbbbo.lllll..",
    ".lll....obbbbbbbbbbbbbbo...lll..",
    "........oobbbbbbbbbbbboo........",
    ".........obbbbbbbbbbbbo.........",
    "..........oobbbbbbbboo..........",
    "...........oobbbbbboo...........",
    ".............oooooo.............",
    "................................",
    "................................",
};


// ---- CHEFE: lacraia com chifres (48x48; desenhada em 4 quadrantes) ----
static const char *const INS_BOSS48[48] =
{
    "...........oo........oo...oo........oo..........",
    "............oo.....................oo...........",
    "....................oo.....oo...................",
    "..............oo.................oo.............",
    "....................oo.....oo...................",
    "................oo.............oo...............",
    "....................oooooooo....................",
    "..................ooobbbbbboooo.................",
    "................oobbbbbbbbbbbboo................",
    "...............oobbbbbbbbbbbbbboo...............",
    "..............oobbbbhhhhhhhhbbbboo..............",
    "..............obbbbbbbbbbbbbbbbbbo..............",
    "..............obbbbhebbbbbbbhebbbo..............",
    "..............obbbbeebbbbbbbeebbbo..............",
    "..............obbbbbbbbbbbbbbbbbbo..............",
    "..............obbbbbbbbbbbbbbbbbbo..............",
    "..............oobbbbbbbbbbbbbbbboo..............",
    "...............oobbbbbbbbbbbbbboo...............",
    "................oobbbbbbbbbbbboo................",
    "...............oobbbhhhhhhhhbbboo...............",
    "...........llllobbbbbbbbbbbbbbbbolll............",
    "...........llloobbbbbbbbbbbbbbbbooll............",
    "...........llllobbbbbbbbbbbbbbbbolll............",
    "...............oobbbbbbbbbbbbbboo...............",
    "................oobbbbbbbbbbbboo................",
    "................oobbhhhhhhhhbboo................",
    "............llllobbbbbbbbbbbbbbolll.............",
    "............llloobbbbbbbbbbbbbbooll.............",
    "............llllobbbbbbbbbbbbbbolll.............",
    "................oobbbbbbbbbbbboo................",
    "..................oobbbbbbbboo..................",
    "............llll.obbbhhhhhhbbbollll.............",
    "............llllobbbbbbbbbbbbbbolll.............",
    "............llllobbbbbbbbbbbbbbolll.............",
    ".................obbbbbbbbbbbbo.................",
    "..................oobbbbbbbboo..................",
    "..................obbhhhhhhbbo..................",
    ".............llllobbbbbbbbbbbbolll..............",
    ".............llllobbbbbbbbbbbbolll..............",
    ".............llll.obbbbbbbbbbollll..............",
    "....................obhhhhbo....................",
    "..............llll.obbbbbbbbollll...............",
    "..............llll.bbbbbbbbbbllll...............",
    "..............llll.obbbbbbbbollll...............",
    "....................obbbbbbo....................",
    "................llllobhhhhbolll.................",
    "................llllobbbbbbolll.................",
    "................llllobbbbbbolll.................",
};

#endif // INSECTS_DATA_H
